#
# Implements a proxy/gateway for Apache.
# # Required modules: mod_proxy, mod_proxy_http
#
<IfModule proxy_module>
    <IfModule proxy_http_module>

        # Commandor v1 ===>>>>
		ProxyPass        /jwas/jwservlet13     http://127.0.0.1:8080/jwas/jwservlet
		ProxyPassReverse /jwas/jwservlet13     http://127.0.0.1:8080/jwas/jwservlet

		ProxyPass        /jwas/msgservlet      http://127.0.0.1:8080/jwas/msgservlet
		ProxyPassReverse /jwas/msgservlet      http://127.0.0.1:8080/jwas/msgservlet
        # <<<=== Commandor v1


        # Commandor v2 ===>>>>
        ProxyPass        /commandor2/websocket ws://127.0.0.1:8081/commandor-websocket/websocket
        ProxyPass        /commandor2/api/      http://127.0.0.1:8081/
        ProxyPassReverse /commandor2/api/      http://127.0.0.1:8081/

        # <<<=== Commandor v2

	</IfModule>
</IfModule>
