log4j.appender.Console=org.apache.log4j.ConsoleAppender
log4j.appender.Console.layout=org.apache.log4j.PatternLayout
log4j.appender.Console.layout.ConversionPattern=%d %-5p - %-255m  %c%n
log4j.appender.File=org.apache.log4j.RollingFileAppender
log4j.appender.File.Append=true
log4j.appender.File.File=${log.home}/commandor1/jwas.log
log4j.appender.File.layout=org.apache.log4j.PatternLayout
log4j.appender.File.layout.ConversionPattern=%d %-5p - %-200m %c [%t]%n
log4j.appender.File.MaxFileSize=4096000
log4j.appender.File.MaxBackupIndex=20
log4j.appender.Default=org.apache.log4j.RollingFileAppender
log4j.appender.Default.Append=true
log4j.appender.Default.File=${log.home}/commandor1/default.log
log4j.appender.Default.layout=org.apache.log4j.PatternLayout
log4j.appender.Default.layout.ConversionPattern=%d %-5p - %-200m %c [%t]%n
log4j.appender.Default.MaxFileSize=4096000
log4j.appender.Default.MaxBackupIndex=60
log4j.appender.SAP=org.apache.log4j.RollingFileAppender
log4j.appender.SAP.Append=true
log4j.appender.SAP.File=${log.home}/commandor1/sap.log
log4j.appender.SAP.layout=org.apache.log4j.PatternLayout
log4j.appender.SAP.layout.ConversionPattern=%d %-5p - %-200m %c [%t]%n
log4j.appender.SAP.MaxFileSize=4096000
log4j.appender.SAP.MaxBackupIndex=20
log4j.appender.Tubes=org.apache.log4j.RollingFileAppender
log4j.appender.Tubes.Append=true
log4j.appender.Tubes.File=${log.home}/commandor1/tubes.log
log4j.appender.Tubes.layout=org.apache.log4j.PatternLayout
log4j.appender.Tubes.layout.ConversionPattern=%d %-5p - %-200m %c [%t]%n
log4j.appender.Tubes.MaxFileSize=4096000
log4j.appender.Tubes.MaxBackupIndex=20
log4j.appender.Caps=org.apache.log4j.RollingFileAppender
log4j.appender.Caps.Append=true
log4j.appender.Caps.File=${log.home}/commandor1/capsules.log
log4j.appender.Caps.layout=org.apache.log4j.PatternLayout
log4j.appender.Caps.layout.ConversionPattern=%d %-5p - %-200m %c [%t]%n
log4j.appender.Caps.MaxFileSize=4096000
log4j.appender.Caps.MaxBackupIndex=20
log4j.appender.Notifs=org.apache.log4j.RollingFileAppender
log4j.appender.Notifs.Append=true
log4j.appender.Notifs.File=${log.home}/commandor1/notif.log
log4j.appender.Notifs.layout=org.apache.log4j.PatternLayout
log4j.appender.Notifs.layout.ConversionPattern=%d %-5p - %-200m %c [%t]%n
log4j.appender.Notifs.MaxFileSize=4096000
log4j.appender.Notifs.MaxBackupIndex=5
log4j.appender.CapsCatroux=org.apache.log4j.RollingFileAppender
log4j.appender.CapsCatroux.Append=true
log4j.appender.CapsCatroux.File=${log.home}/commandor1/capsulescatroux.log
log4j.appender.CapsCatroux.layout=org.apache.log4j.PatternLayout
log4j.appender.CapsCatroux.layout.ConversionPattern=%d %-5p - %-200m %c [%t]%n
log4j.appender.CapsCatroux.MaxFileSize=4096000
log4j.appender.CapsCatroux.MaxBackupIndex=20
log4j.appender.JDBC=org.apache.log4j.jdbcplus.JDBCAppender
log4j.appender.JDBC.dbclass=net.sourceforge.jtds.jdbc.Driver
log4j.appender.JDBC.url=jdbc:jtds:sqlserver://BLO-SQL-PROD01/pg_commandorv1;instance=COMMANDOR;autoReconnect=true
log4j.appender.JDBC.username=SQL-COMMANDOR-RW
## TODO : Set SQL-COMMANDOR-RW password
log4j.appender.JDBC.password=
log4j.appender.JDBC.sql=INSERT INTO LOG_APPLICATION (horodate,categorie,niveau,message,source,thread,trace) VALUES (CURRENT_TIMESTAMP,'SRV_APP','@PRIO@','@MSG@','@CAT@','@THREAD@','@THROWABLE@');
log4j.appender.JDBC.layout=org.apache.log4j.PatternLayout
log4j.rootLogger=INFO,Console,File,JDBC
log4j.logger.procter.server.kanban.sap=INFO,SAP
log4j.logger.procter.server.kanban.ligne=INFO,Default
log4j.logger.procter.server.kanban.navette=INFO,Default
log4j.logger.procter.server.kanban.tubescatroux=INFO,Tubes
log4j.logger.procter.server.kanban.rtcis=INFO,Default
log4j.logger.procter.server.kanban.capscatroux=INFO,CapsCatroux
log4j.logger.procter.server.kanban.caps=INFO,Caps
log4j.logger.procter.server.kanban.notif.WTDbNotif=INFO,Notifs
